-- Őrszem V2 — Phase 2: identity, sessions and audit.
--
-- The first real V2 migration. Once applied to a persistent environment this file is
-- immutable: corrections arrive as new forward migrations, never as edits here.
--
-- Scope is deliberately exactly Phase 2. No service areas, reports, taxonomy or
-- moderation tables — those arrive with the features that need them.
--
-- Conventions:
--   * UUID primary keys, generated by the application, not by the database.
--   * Enumerations are VARCHAR + CHECK, not native PostgreSQL enums: adding a value to a
--     native enum is a schema migration with awkward transactional semantics, while a
--     CHECK constraint is a plain, reversible DDL statement.
--   * All timestamps are TIMESTAMPTZ and written as UTC Instants.
--   * Token secrets are stored as BYTEA SHA-256 digests, never as text and never in
--     plaintext.

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
-- The service ID is a pseudonymous identity. No name, e-mail, phone, address, date of
-- birth or employment data is stored: Phase 2 has no need for it, and personal data that
-- is never collected cannot leak.
CREATE TABLE users (
    id                    UUID         PRIMARY KEY,
    service_id            VARCHAR(9)   NOT NULL,
    role                  VARCHAR(32)  NOT NULL,
    status                VARCHAR(32)  NOT NULL,
    password_hash         TEXT         NOT NULL,
    must_change_password  BOOLEAN      NOT NULL DEFAULT TRUE,
    password_changed_at   TIMESTAMPTZ  NULL,
    created_at            TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ  NOT NULL,

    -- The canonical service ID shape, enforced by the database rather than trusted from
    -- application code: SZ- followed by exactly six decimal digits.
    CONSTRAINT ck_users_service_id_shape CHECK (service_id ~ '^SZ-[0-9]{6}$'),
    CONSTRAINT ck_users_role   CHECK (role   IN ('SERVICE_USER', 'MODERATOR', 'SUPER_ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DEACTIVATED'))
);

-- The final authority on service-ID collisions. The generator retries against this.
-- A deactivated user keeps its row, so its service ID is never handed out again.
CREATE UNIQUE INDEX ux_users_service_id ON users (service_id);

-- ---------------------------------------------------------------------------
-- auth_sessions
-- ---------------------------------------------------------------------------
-- One row per server-side session. The access token is opaque: it carries no claims, so
-- role and account state are always read from the database at request time and a
-- deactivation or role change takes effect immediately.
CREATE TABLE auth_sessions (
    id                       UUID         PRIMARY KEY,
    user_id                  UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    access_secret_hash       BYTEA        NOT NULL,
    access_token_expires_at  TIMESTAMPTZ  NOT NULL,
    created_at               TIMESTAMPTZ  NOT NULL,
    -- Absolute end of the session. Refreshing issues new tokens but can never move this,
    -- so there is no infinite sliding session.
    session_expires_at       TIMESTAMPTZ  NOT NULL,
    revoked_at               TIMESTAMPTZ  NULL,
    revocation_reason        VARCHAR(64)  NULL,

    CONSTRAINT ck_auth_sessions_revocation
        CHECK ((revoked_at IS NULL) = (revocation_reason IS NULL))
);

-- Lookups by user: logout-all, and revoking every session on a password change.
CREATE INDEX ix_auth_sessions_user ON auth_sessions (user_id);
-- Supports finding the still-live sessions of a user without scanning revoked history.
CREATE INDEX ix_auth_sessions_active ON auth_sessions (user_id, session_expires_at)
    WHERE revoked_at IS NULL;
-- Retention: lets a future cleanup job find expired sessions cheaply. No scheduler is
-- introduced in Phase 2; see docs/architecture/adr/0004 for the retention obligation.
CREATE INDEX ix_auth_sessions_expiry ON auth_sessions (session_expires_at);

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------------
-- Rotating refresh tokens. A consumed row is deliberately kept for the life of the
-- session: that history is what makes replay detectable. Deleting consumed rows eagerly
-- would silently disable reuse detection.
CREATE TABLE refresh_tokens (
    id                     UUID         PRIMARY KEY,
    session_id             UUID         NOT NULL REFERENCES auth_sessions (id) ON DELETE CASCADE,
    secret_hash            BYTEA        NOT NULL,
    created_at             TIMESTAMPTZ  NOT NULL,
    expires_at             TIMESTAMPTZ  NOT NULL,
    consumed_at            TIMESTAMPTZ  NULL,
    replaced_by_token_id   UUID         NULL REFERENCES refresh_tokens (id) ON DELETE SET NULL
);

CREATE INDEX ix_refresh_tokens_session ON refresh_tokens (session_id);
-- Retention: supports future cleanup of long-expired tokens.
CREATE INDEX ix_refresh_tokens_expiry ON refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- audit_events
-- ---------------------------------------------------------------------------
-- Append-only record of security-sensitive state changes, written in the same
-- transaction as the change itself. This is not event sourcing: the tables above remain
-- the source of truth, and these rows are an immutable trail beside them.
--
-- Failed login guesses are NOT audited here — they are security logging. Auditing every
-- guess would let an attacker flood the table.
--
-- metadata must never contain a password, password hash, temporary credential, access
-- token, refresh token or token hash.
CREATE TABLE audit_events (
    id             UUID         PRIMARY KEY,
    -- Groups the rows written by one logical operation (a password change revoking many
    -- sessions writes several rows sharing one operation_id).
    operation_id   UUID         NOT NULL,
    actor_type     VARCHAR(16)  NOT NULL,
    -- NULL for SYSTEM actors, such as the maintenance CLI.
    actor_user_id  UUID         NULL REFERENCES users (id) ON DELETE SET NULL,
    event_type     VARCHAR(64)  NOT NULL,
    target_type    VARCHAR(32)  NOT NULL,
    target_id      UUID         NULL,
    metadata       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_audit_actor_type CHECK (actor_type IN ('USER', 'SYSTEM')),
    -- A USER actor must say who; a SYSTEM actor must not claim a user.
    CONSTRAINT ck_audit_actor_user CHECK (
        (actor_type = 'USER'   AND actor_user_id IS NOT NULL) OR
        (actor_type = 'SYSTEM' AND actor_user_id IS NULL)
    )
);

CREATE INDEX ix_audit_events_created  ON audit_events (created_at);
CREATE INDEX ix_audit_events_target   ON audit_events (target_type, target_id);
CREATE INDEX ix_audit_events_actor    ON audit_events (actor_user_id);
CREATE INDEX ix_audit_events_type     ON audit_events (event_type, created_at);
CREATE INDEX ix_audit_events_operation ON audit_events (operation_id);
