package hu.orszembejelento.app.report.domain

import java.security.SecureRandom
import java.util.Base64

/**
 * A Public report's access capability, generated by this client - never by the backend
 * (Phase 5 brief §6, mirroring the server's own ADR 0008 design).
 *
 * Exact shape the backend validates: `pr_` followed by 43 URL-safe base64 characters, the
 * unpadded encoding of exactly 32 bytes (256 bits) of randomness. [SecureRandom] only -
 * never `kotlin.random.Random`, `java.util.Random`, or anything seeded/deterministic. This
 * value is sent as the `X-Orszem-Report-Access` header; it is never logged, never put in a
 * URL, and [toString] deliberately does not print it.
 */
@JvmInline
value class ReportAccessCredential private constructor(val value: String) {

    override fun toString(): String = "ReportAccessCredential(**redacted**)"

    companion object {
        private const val PREFIX = "pr_"
        private val PATTERN = Regex("^pr_[A-Za-z0-9_-]{43}$")
        private val secureRandom = SecureRandom()

        /** Generates a fresh, cryptographically random credential. Called once per new report. */
        fun generate(): ReportAccessCredential {
            val bytes = ByteArray(32)
            secureRandom.nextBytes(bytes)
            val encoded = PREFIX + Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
            check(PATTERN.matches(encoded)) { "generated credential does not match the expected shape" }
            return ReportAccessCredential(encoded)
        }

        /** Reconstructs a credential from a value this app already generated and stored. */
        fun ofStored(value: String): ReportAccessCredential? =
            if (PATTERN.matches(value)) ReportAccessCredential(value) else null
    }
}
