package hu.orszembejelento.backend.reports.domain

import java.security.MessageDigest

/**
 * A Public report's access capability - the only thing that stands between an anonymous
 * report and anyone who can guess its public ID (ADR 0008).
 *
 * **Generated by the client, before the first submission attempt - never by the backend.**
 * The backend never issues one and never needs to: it only validates the *shape*
 * (`pr_` followed by exactly 43 URL-safe base64 characters - the unpadded encoding of
 * exactly 256 random bits) and stores [PublicReportAccessCredentialHasher]'s SHA-256 of it.
 * It cannot, and does not need to, prove the client's randomness was any good - a
 * deliberately weak credential from a malicious or broken client compromises only that
 * client's own report, never anyone else's, because every report has an independent
 * credential.
 *
 * Sent as the `X-Orszem-Report-Access` header on every request that needs it: the initial
 * `POST`, an idempotent retry of it, and every later `GET`. Never a query parameter, a path
 * segment, a cookie, or a response body - see the Public report endpoints.
 */
@JvmInline
value class PublicReportAccessCredential private constructor(val value: String) {

    override fun toString(): String = "PublicReportAccessCredential(**redacted**)"

    companion object {
        private const val PREFIX = "pr_"

        // 43 characters: the unpadded base64url encoding of exactly 32 bytes (256 bits).
        private val PATTERN = Regex("^pr_[A-Za-z0-9_-]{43}$")

        fun parseOrNull(raw: String?): PublicReportAccessCredential? {
            val trimmed = raw?.trim() ?: return null
            return if (PATTERN.matches(trimmed)) PublicReportAccessCredential(trimmed) else null
        }
    }
}

/**
 * Hashes and verifies a [PublicReportAccessCredential]. Never Argon2 or any other
 * password-hashing scheme: the credential already carries uniformly random 256-bit
 * entropy by construction (unlike a human-chosen password), so a fast cryptographic hash
 * is the correct tool, and deliberately slowing verification down would buy nothing here.
 */
object PublicReportAccessCredentialHasher {

    /** SHA-256 of the credential's exact string form. Never the plaintext credential itself. */
    fun hash(credential: PublicReportAccessCredential): ByteArray =
        MessageDigest.getInstance("SHA-256").digest(credential.value.toByteArray(Charsets.UTF_8))

    /**
     * Constant-time comparison against a stored hash.
     *
     * [MessageDigest.isEqual] is specified to take time depending only on the compared
     * lengths, never on where the first differing byte falls - exactly what a credential
     * comparison needs, without hand-rolling a constant-time loop.
     */
    fun matches(credential: PublicReportAccessCredential, storedHash: ByteArray): Boolean =
        MessageDigest.isEqual(hash(credential), storedHash)
}
