package hu.orszembejelento.backend.common.web

/**
 * Stable, machine-readable error codes.
 *
 * Clients switch on [ErrorCode]; they must never parse `message`, which is human-facing
 * and may be reworded or translated at any time.
 *
 * Several distinct internal situations map onto one code on purpose — see
 * [INVALID_CREDENTIALS] and [SESSION_INVALID].
 */
enum class ErrorCode {
    /**
     * Returned identically for an unknown service ID, a wrong password and a deactivated
     * account. Telling these apart would let anyone enumerate valid service IDs, or learn
     * that an account exists but is disabled.
     */
    INVALID_CREDENTIALS,

    /**
     * The credentials were correct, but the account still owes its initial password
     * change. No session is issued. This is intentionally distinguishable from
     * [INVALID_CREDENTIALS]: it is only reachable by someone who already proved they hold
     * the temporary credential, so it discloses nothing to an attacker.
     */
    PASSWORD_CHANGE_REQUIRED,

    PASSWORD_POLICY_VIOLATION,

    /**
     * Covers every way an access or refresh credential can fail: malformed, unknown,
     * expired, consumed, revoked, or belonging to a session whose user is no longer
     * permitted. Deliberately undifferentiated so the response never reveals the internal
     * token structure or how far a guess progressed.
     */
    SESSION_INVALID,

    RATE_LIMITED,
    VALIDATION_ERROR,
    INTERNAL_ERROR,

    /**
     * No reference dataset has ever been successfully imported. Returned with HTTP 503 by
     * the Public reference endpoints instead of an empty 200, which would look like a
     * verified "nothing found" answer rather than "the backend has nothing loaded yet" -
     * see ADR 0007.
     */
    REFERENCE_DATASET_UNAVAILABLE,

    /**
     * The `X-Orszem-Report-Access` header is missing or malformed, on **creation** only -
     * see `GetPublicReportUseCase` and `InvalidReportAccessCredentialException` for why the
     * lookup path never uses this code.
     */
    INVALID_REPORT_ACCESS_CREDENTIAL,

    /** `eventTypeCode` is unknown or not active. */
    INVALID_EVENT_TYPE,

    /** `settlementId` is unknown or not active. */
    INVALID_SETTLEMENT,

    /** `railwayLineId` was supplied but is unknown. */
    INVALID_RAILWAY_LINE,

    /**
     * `clientSubmissionId` already names a report whose stored payload or credential does
     * not match this request - see `IdempotencyKeyReusedException`.
     */
    IDEMPOTENCY_KEY_REUSED,

    /**
     * Returned identically for an unknown public report id, a missing credential, a
     * malformed credential, and a wrong credential - see `ReportNotFoundException`.
     */
    REPORT_NOT_FOUND,
}

/**
 * The single error shape returned by the API.
 *
 * [correlationId] is generated by the server for every request and is echoed here and in
 * the `X-Correlation-Id` response header, so a user-reported failure can be tied to
 * server logs without exposing anything about the failure itself.
 */
data class ErrorResponse(
    val code: ErrorCode,
    val message: String,
    val correlationId: String,
)
